#!/bin/bash

## Variables ##
dryrun="no"
D="-------"
bkpdate=$(date +"%Y%m%d")
bkplog="/var/log/backups/$bkpdate.log"
bkpdst="/mnt/backups"
ncdir="/srv/www/nextcloud"
direxcl="$ncdir/data/updater-"
dbhost=$(grep dbhost $ncdir/config/config.php | awk -F "'" '{print $4}' | awk -F ":" '{print $1}')
dbport=$(grep dbhost $ncdir/config/config.php | awk -F "'" '{print $4}' | awk -F ":" '{print $2}')
dbuser=$(grep dbuser $ncdir/config/config.php | awk -F "'" '{print $4}')
dbpwd=$(grep dbpassword $ncdir/config/config.php | awk -F "'" '{print $4}')
dbname=$(grep dbname $ncdir/config/config.php | awk -F "'" '{print $4}')

## Functions ##
# Print to log #
print_log()
{
	delimiter="----------------$D-----------------------"
	logstamp="----- Backup $1: $(date +'%Y-%m-%d') $(date +'%H-%M-%S') -----"
	case $1 in
		start)
			echo -e "\n$delimiter\n$logstamp" >>$bkplog
			;;
		end)
			echo -e "\n$logstamp\n$delimiter\n" >>$bkplog
	esac
}

# Setting maintenance mode on Nextcloud instance #
maint_mode()
{
	mode=$(printf '%s\n' "$1" | awk '{ print toupper($0) }')
	echo -e "\n--- Maintenance mode $mode ---" >>$bkplog
	if [ "$dryrun" == "no"  ] ; then
		sudo -u www-data php $ncdir/occ maintenance:mode --$1 >>$bkplog 2>&1
		if [ $? -ne 0 ] ; then
			echo "-> Setting maintenance mode '$mode': Failed! (exit code: $?)" >>$bkplog
			exit 1
		else
			echo "-> Setting maintenance mode '$mode': OK" >>$bkplog
		fi
	fi
}

# MySQL database export #
db_dump()
{
	echo -e "\n--- DataBase Export ---" >>$bkplog
	if [ "$dryrun" == "no"  ] ; then
		mysqldump --single-transaction -h "$dbhost" -P "$dbport" -u "$dbuser" -p"$dbpwd" "$dbname" > $bkpdst/nextcloud-sqlbkp_$bkpdate.sql 2>>$bkplog
		if [ $? -ne 0 ] ; then
			echo "-> DataBase export: Failed! (exit code: $?)" >>$bkplog
			exit 1
		else
			echo "-> DataBase export: OK" >>$bkplog
		fi
	fi
}

# Folder archival #
folder_archive()
{
	echo -e "\n--- Folder archival ---" >>$bkplog
	if [ "$dryrun" == "no" ] ; then
		tar -czf $bkpdst/nextcloud-dirbkp_$bkpdate.tgz --exclude="$direxcl*" $ncdir/ 2>>$bkplog
		if [ $? -ne 0 ] ; then
			echo "-> Folder archive: Failed! (exit code: $?)" >>$bkplog
			exit 1
		else
			echo "-> Folder archive: OK" >>$bkplog
		fi
	fi
}

## Main ##
while getopts "d" option
do
	case $option in
		d)
			dryrun="yes"
			D="DRY-RUN"
			;;
	esac
done

print_log start
maint_mode on
db_dump
folder_archive
maint_mode off
print_log end
exit 0
